name: tappuu_app
description: "Tappuu."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  intl: ^0.20.2
  http: ^1.6.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.4
  path: ^1.8.0
  google_fonts: ^6.3.3
  flutter_screenutil: ^5.9.3
  skeletonizer: ^2.1.2
  flutter_map: ^8.2.2
  geolocator: ^14.0.2

  image_picker: ^1.2.1
  translator: ^1.0.3+1
  smooth_page_indicator: ^2.0.1
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.5
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^2.0.5

  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  firebase_messaging: ^16.1.0

  app_links: ^7.0.0
  share_plus: ^12.0.1
  permission_handler: ^12.0.1
  collection: ^1.16.0
  photo_view: ^0.15.0
  shimmer: ^3.0.0
  dotted_border: 2.1.0
  file_picker: ^10.3.0
  video_player: ^2.5.1
  chewie: ^1.5.0
  googleapis_auth: ^2.0.0
  speech_to_text: ^7.3.0
  mic_stream_recorder: ^1.1.2
  audioplayers: ^6.5.1
  flutter_gcaptcha_v3: ^2.1.1

  webview_flutter: ^4.13.0
  webview_flutter_wkwebview: ^3.23.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

flutter_native_splash:
  color: "#FFC813"
 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/play_store_512.png"
  adaptive_icon_background: "#FFC813"
  adaptive_icon_foreground: "assets/images/play_store_512.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/icon/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
